### PR TITLE
Fix single-choice to use radio buttons

### LINKED ISSUE #1: radio-button item-control not working
http://hl7.org/fhir/R4/valueset-questionnaire-item-control.html

radio-button is required for when only a single selection is possible. Currently check-box is implemented with this behaviour.

### PR DESCRIPTION
**Pull request by johngrimes**
Resolves #1.

### CODE REVIEW

**Comment by johngrimes** [comment]
I'll review this.

**Comment by johngrimes** [comment]
@yeexianfong This change looks good.

I'd also like you to implement a minimal automated test that verifies that this change fixes this issue.

**Comment by yeexianfong** [comment]
@johngrimes just pushed my working tests, can you kindly review and i will merge the PR after

**Comment by johngrimes** [comment]
Looks good to me!

**Pull request merged**
