### PR TITLE
Fix AnswerValueSet to reference value set url only

### LINKED ISSUE #2: answerValueSet canonical reference
answerValueSet works when referencing an expansion request to the configured terminology server, https://r4.ontoserver.csiro.au/fhir

e.g. 
`"linkId": "a5e9f87a-c561-4ffb-b200-9b93b8887a11",
                            "text": "item",
                            "code": [{"code": "282291009", "display": "Diagnosis interpretation" }],
                            "type": "open-choice",
                            "repeats": true,
                            "answerValueSet": "https://r4.ontoserver.csiro.au/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/(%5E%2032570071000036102%20OR%20%5E%2032570141000036105)&"`

answerValueSet should reference the value set url.

answerValueSet should be able to draw values from a value set in the configured terminology server or a contained value set.

### PR DESCRIPTION
**Pull request by yeexianfong**
Resolves #2.

To reiterate, answerValueSet in questionnaire data should be set to
```
"answerValueSet": "http://snomed.info/sct?fhir_vs=ecl/(%5E%2032570071000036102%20OR%20%5E%2032570141000036105)&"
```
instead of
```
"answerValueSet": "https://r4.ontoserver.csiro.au/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/(%5E%2032570071000036102%20OR%20%5E%2032570141000036105)&"
```

### CODE REVIEW

**Comment by yeexianfong** [comment]
Next step is to write tests to test autocomplete in the text box

**Comment by yeexianfong** [comment]
Another thing to discuss is to potentially find and replace all occurrences of the ontoserver link in answervalueset in all questionnaire datasets - only leaving value set url as the answerValueSet value

**Comment by yeexianfong** [comment]
Lets wait until I finish my code review with Heath next Wednesday before merging.
We also need to update the Questionnaires before we merge.

**Comment by johngrimes** [comment]
Ok, I will hold off on reviewing this one.

**Pull request closed without merging**
